menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: false
disqus_shortname:

# LiveRe 来必力
livere: false
livere_data_uid: 

# google analytics
googleTrackId: 
